default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    []

  javascripts:    []

_smartphone:
  has_layout:     true
  layout:         smartphone
  metas:
    viewport: width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no

_another:
  has_layout:     true
  layout:         layoutC
